feat: add sf-org-open commends (+ open current file)
xixiaofinland/sf.nvim pull request #130
Opened 2024-07-17 16:06 UTC by ognjen-vuceljic

I added `sf org open` with the option to open the org, as well as the current file (e.g. flow)

This does not perform a lot of validation, though, so it's the user's responsibility to make sure they can use `sf org --source-file ...` properly.

Happy to hear some thoughts!

2024-07-17 16:57 UTC, xixiaofinland requested changes
I think they suit more into `org.lua` rather than `term.lua`, reasons:

1. Their features are about "org"
2. They don't need to open the term, it's better to do silent run in the background just like other functions in org.lua

You can use `silent_job_call` in `Util.lua` to call the commands to run in the background.

In addition, if they are in `org.lua`, the naming can be shortened.

2024-07-17 17:15 UTC, xixiaofinland requested changes

2024-07-17 17:15 UTC, xixiaofinland commented on lua/sf/term.lua
> +	local cmd = vim.fn.expandcmd('sf org open --source-file "%:p"')
For constructing commands against the target-org, I suggest always be specific and give `U.get()` at the end (example below). It's wise that we don't trust `sf` handling it implicitly. 

Also in case the default target org is not set, `U.get()` will throw error.
```
local cmd = vim.fn.expandcmd('sf project retrieve start -d "%:p" -o ') .. U.get()
 ```

2024-07-17 17:15 UTC, xixiaofinland commented on lua/sf/term.lua
> +	local cmd = vim.fn.expandcmd('sf org open')
there is nothing to expand in this cmd, use` local cmd = 'sf org open'` is fine.

2024-07-17 17:22 UTC, ognjen-vuceljic commented
@xixiaofinland  I'm having some issues with IDE, so i have to apply a bunch of smaller commits.

Changes should be there now.

Please let me know if I missed anything, and thanks for suggestions!

2024-07-17 17:31 UTC, xixiaofinland commented on lua/sf/org.lua
> +  local org = string.gsub(choice, '%[S%] ', '')
In the plugin's scenario, I think it's better that the error message shows the specific `sf` command that failed. After all, this is a developer tool, telling the command is more useful.

If it's a business user tool, I agree abstract ordinary error makes sense.

Just FYI, I will approve the PR and update this little part. :)

2024-07-17 17:31 UTC, xixiaofinland approved these changes

2024-07-17 17:31 UTC, merged

2024-07-17 18:03 UTC, xixiaofinland commented
@ognjen-vuceljic 
I added a commit after the PR approval to tweak some small things.

One question, how does `sf org open --source-file` really work? Does it work only for pages? I read `sf org open --help` but still not fully get it.

If it works oddly/in unexpected behavior, I might consider disabling the `sO` default key.

2024-07-17 20:22 UTC, ognjen-vuceljic commented
@xixiaofinland  In theory, the `sf org open --source-file` should open the current file that we specify.

Since it works well for flows, and it might be a useful feature, can we modify the list of `defaults` in `config.lua` to include `Flow` metadata type?

As it stands right now, the `sO` hotkey won't be run when we are in Flow, since this metadata type is not added to defaults. It works from APEX code, but the command itself will open a Lightning App Builder instead of APEX class, which is a `sf` issue I guess.

So far I noticed that the main use case for `--source-file` is opening a Flow directly via `sf` command

2024-07-18 06:50 UTC, xixiaofinland commented
> can we modify the list of `defaults` in `config.lua` to include `Flow` metadata type?

It's part of the default configuration, thus meant to be adjusted by users according to each's individual needs.
Is flow a xml file? you can add it into your `setup` like below.

```lua
require('sf').setup({
   // other own settings you already have;
   hotkeys_in_filetypes = {
    "apex", "sosl", "soql", "javascript", "html", "xml"
  },
})
```
```